#!/bin/bash

# ubuntu:
#	- install go, git, tmux, clang, libclang, ruby-dev
#	- vim should be built with python/ruby/lua support
# mac:
#	- install brew
#	- install coreutils: http://www.topbug.net/blog/2013/04/14/install-and-use-gnu-command-line-tools-in-mac-os-x/
#	- install vim: brew install macvim --with-cscope --with-lua --HEAD --override-system-vim

set -e

vim_bundle_dir=~/.vim_bundle
vim_tmpdir=~/.vim_tmp

setup_vim() {
	[ ! -d $vim_tmpdir ] && (rm -rf $vim_tmpdir && mkdir -p $vim_tmpdir)

	rm -rf ~/.config/nvim && ln -s ~/.vim ~/.config/nvim
	ln -sfv ~/.vimrc ~/.config/nvim/init.vim

	# plug
	curl -fLo ~/.vim/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
	vim +PlugUpdate +qall
	#vim -N -u ~/.vimrc -c "PlugUpdate" -c 'qa!' -U NONE -i NONE -V1 -e -s || true

	vim -N -u ~/.vimrc /tmp/a.go -c "GoUpdateBinaries" -c 'qa!' -U NONE -i NONE -V1 -e -s || true
	echo
}

make_link() {
	from=$1
	to=$2

	if [ -e "$to" ]; then
		rm -rf "$to.old" && mv -f "$to" "$to.old"
	fi

	ln -sfv "$from" "$to"
}

files=(
	bashrc
	bash_prompt
	bash_aliases
	bash_profile
	gitconfig
	screenrc
	toprc
	gdbinit
	tmux.conf
	profile
	vimrc
	vim
	tmux-mac.conf
	tmux-linux.conf
	inputrc
)

setup_link() {
	for f in "${files[@]}"; do
		make_link "$PWD/$f" ~/."$f"
	done

	if [[ $OSTYPE =~ darwin* ]]; then
		for f in vscode/*; do
			make_link "$PWD/$f" ~/"Library/Application Support/Code/User/$(basename $f)"
		done
	fi

    touch ~/.bash_sessions_disable
}

install_or_update() {
	setup_link
	. ~/.profile
	./update-files
	setup_vim
}

install_or_update

# vim: noet
