#!/bin/bash

# ubuntu:
#	- install go, git, tmux, clang, libclang, ruby-dev
#	- vim should be built with python/ruby/lua support
# mac:
#	- install brew
#	- install coreutils: http://www.topbug.net/blog/2013/04/14/install-and-use-gnu-command-line-tools-in-mac-os-x/
#	- install vim: brew install macvim --with-cscope --with-lua --HEAD --override-system-vim

set -e

vim_bundle_dir=~/.vim_bundle
vim_tmpdir=~/.vim_tmp

setup_vim() {
	[ ! -d $vim_tmpdir ] && (rm -rf $vim_tmpdir && mkdir -p $vim_tmpdir)

	# neobundle
	[ ! -d $vim_bundle_dir ] && (rm -rf $vim_bundle_dir && mkdir -p $vim_bundle_dir)
	[ ! -d $vim_bundle_dir/neobundle ] && git clone http://github.com/Shougo/neobundle.vim $vim_bundle_dir/neobundle
	~/.vim_bundle/neobundle/bin/neoinstall

	vim -N -u ~/.vimrc /tmp/a.go -c "GoUpdateBinaries" -c 'qa!' -U NONE -i NONE -V1 -e -s || true
	echo
}

make_link() {
	from=$1
	to=$2

	if [ -e "$to" ]; then
		rm -rf "$to.old" && mv -f "$to" "$to.old"
	fi

	ln -sfv "$from" "$to"
}

files=(
	bashrc
	bash_prompt
	bash_aliases
	gitconfig
	screenrc
	toprc
	gdbinit
	tmux.conf
	profile
	vimrc
	vim
	hgrc
	tmux-mac.conf
	tmux-linux.conf
	inputrc
)

setup_link() {
	for f in "${files[@]}"; do
		make_link "$PWD/$f" ~/."$f"
	done

    touch ~/.bash_sessions_disable
}

install_or_update() {
	setup_link
	. ~/.profile
	./update-files
	setup_vim
}

install_or_update

# vim: noet
