#!/bin/bash

set -e

# dircolors
url=https://raw.github.com/seebi/dircolors-solarized/master/dircolors.256dark
echo ">>> updating dirclors files..."
curl -# -L "$url" -o ~/.dircolors

# git completion
url_prefix=https://raw.github.com/git/git/master/contrib/completion
echo ">>> updating git files..."
curl -# -L $url_prefix/git-completion.bash -o ~/.git-completion.bash
curl -# -L $url_prefix/git-prompt.sh -o ~/.git-prompt.sh

# tmux
url='https://raw.githubusercontent.com/przepompownia/tmux-bash-completion/master/completions/tmux'
echo ">>> updating tmux files..."
curl -# -L  "$url" -o ~/.bash_completion_tmux.sh
